USE information_schema;

SELECT
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'admin_placement_db'
AND TABLE_NAME = 'placed_students'
AND REFERENCED_TABLE_NAME IS NOT NULL;

SELECT
    CONSTRAINT_NAME,
    DELETE_RULE,
    UPDATE_RULE
FROM REFERENTIAL_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'admin_placement_db'
AND TABLE_NAME = 'placed_students';
